- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/ansible/ansible-lint
  rev: v5.0.11
  hooks:
    - id: ansible-lint
      args: ['--exclude=roles/junos_*', '--exclude=roles/vyos_*']

